import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { GoogleOAuthProvider } from '@react-oauth/google';

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const clientId = "587184758719-eed0mnubth1t8im1t97f9d88rolns872.apps.googleusercontent.com"; // substitua pelo seu Client ID do Google
//const clientId = "400012015361-tmrebh20g3bt2hgfvdia8ndpruqipoe9.apps.googleusercontent.com"; // substitua pelo seu Client ID do Google

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GoogleOAuthProvider clientId={clientId}>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </GoogleOAuthProvider>

  );
}